services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: todo_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - todo_api_pgdata:/var/lib/postgresql/data

volumes:
  todo_api_pgdata:
